### ISSUE TITLE
Stuck at I'm not a robot

### ISSUE THREAD

**Issue by flashblaze** [uport-project/uport-android#9] opened 2018-09-09 14:47 UTC
I tried using phone verification but it fails. As a result, I tried using captcha. Even after correctly answering at least 5 times, it keeps on looping the verification page. I even tried to verify using audio but it fails at that too.

Device: OnePlus 2
Root: Yes, using Magisk Manager
Android version: 8.1.0 Oreo
Custom ROM: Yes

I even hid the app from root access using Magsik Hide, but to no avail.

Please help.

**Comment by mirceanis** [comment] 2018-09-09 15:53
We don't have a consistent way of reproducing this issue, so I can't guarantee an immediate fix.
As a workaround, please try to clear app data or uninstall/reinstall and then retry onboarding.
It's best to try the sms verification first, since funcaptcha may have issues with custom rom/rooted devices.

**Comment by flashblaze** [comment] 2018-09-09 18:33
I did reinstall the app several times and even cleared the app data but the issue still persists. The SMS verification isn't working in my case. It did work for my friend though who has a non-rooted device.
I'll submit my findings if I find any workaround. Thanks for the prompt reply.

Country: India

**Comment by mirceanis** [comment] 2018-09-09 18:48
Thanks for trying the workaround. I'm sorry it didn't work out.
Note that the number verified doesn't have to be your own, just a valid one to prevent abuse.
I'd still like to understand the problem.
When you say it doesn't work, when does it fail?
Does the sms get delivered?
Does the app show an error when entering the code?

Also note, the next version no longer requires sms or captcha checks. Stay tuned for an update.

**Comment by flashblaze** [comment] 2018-09-09 19:27
No worries. Glad you're working on the next update.
So after the number is inserted, it says sending verification code and after half a second or so, it [displays this](https://imgur.com/a/RsHucCJ). The number is my own cell number, so it should work.

Edit: I have given all the permissions.

**Comment by mirceanis** [comment] 2018-10-15 12:22
I'm closing this since the said update has been released.
If other issues arise please submit them to [uport-mobile-issues](https://github.com/uport-project/uport-mobile-issues/issues)

**Closed as completed by mirceanis** 2018-10-15 12:22 UTC
